version: '3.4'

services:
  crmit-items:
    image: ${DOCKER_REGISTRY-}crmit-items
    build:
      context: .
      dockerfile: src/CRMit.Items/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+
      - CONNECTIONSTRINGS__ITEMSDB=Server=db; Database=ItemsDB; User ID=sa; Password=Password1234;
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/localhost.key
    volumes:
      - ${HOME}/.aspnet/https:/https/
    ports:
      - 8001:443
