name: Release

on:
  push:
    tags:
      - v*

jobs:
  push_tag:
    name: Push tag to Docker repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Fetch tags
        run: git fetch -f --prune --unshallow --tags

      - name: Get last tag
        id: last_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull staging image
        run: docker pull dropik/crmit-items:staging

      - name: Set tag
        run: |
          docker tag dropik/crmit-items:staging dropik/crmit-items:${{ steps.last_tag.outputs.tag }}
          docker tag dropik/crmit-items:staging dropik/crmit-items:latest
      
      - name: Push tag
        run: |
          docker push dropik/crmit-items:${{ steps.last_tag.outputs.tag }}
          docker push dropik/crmit-items:latest

  nuget:
    name: Publish Nuget package
    runs-on: ubuntu-latest
    env:
      PROJECT: src/CRMit.Items/CRMit.Items.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet CLI
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore $PROJECT

      - name: Build
        run: dotnet build --configuration Release --no-restore $PROJECT

      - name: Publish package
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: README.md
          draft: false
          prerelease: false
